apiVersion: apps/v1
kind: Deployment
metadata:
  name: todolist
  labels:
    app: todolist
spec:
  replicas: 4
  selector:
    matchLabels:
      app: todolist
  template:
    metadata:
      labels:
        app: todolist
    spec:
      containers:
      - name: todolist
        image: abhishekkk15/todo_list:latest
        ports:
        - containerPort: 3000