name: Build and Push Docker Image with Tag

on: 
  push: 
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    env:
      GH_PAT: ${{ secrets.GH_PAT }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set IMAGE_TAG (PowerShell)
      shell: powershell
      run: |
        $dateTag = Get-Date -Format "yyyyMMddHHmmss"
        Add-Content -Path $env:GITHUB_ENV -Value "IMAGE_TAG=$dateTag"

    - name: Debug Docker credentials
      shell: powershell
      run: |
        Write-Output "Username: ${{ secrets.DOCKER_USERNAME }}"
        Write-Output "Token length: $($env:DOCKER_PASSWORD.Length)"

    - name: Docker login (PowerShell)
      shell: powershell
      run: |
        docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"

    - name: Build Docker image
      shell: powershell
      run: |
        docker build -t abhishekkk15/todo_list:$env:IMAGE_TAG .

    - name: Push Docker image
      shell: powershell
      run: |
        docker push abhishekkk15/todo_list:$env:IMAGE_TAG

    - name: Update image tag in deployment.yml (PowerShell)
      shell: powershell
      run: |
        (Get-Content "k8s/deployment.yaml") -replace "image: .*/todo_list:.*", "image: abhishekkk15/todo_list:$env:IMAGE_TAG" | Set-Content "k8s/deployment.yaml"

    - name: Commit and push updated YAML (PowerShell)
      shell: powershell
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git config --global credential.helper ""

        git remote set-url origin "https://x-access-token:$($env:GH_PAT)@github.com/Abhishekkkk-15/todo-list.git"

        git add k8s/deployment.yaml
        git commit -m "Update image to $env:GITHUB_SHA"
        if ($LASTEXITCODE -ne 0) {
          Write-Output "No changes to commit"
        } else {
          git push -f "https://x-access-token:$($env:GH_PAT)@github.com/Abhishekkkk-15/todo-list.git" main
        }
